version: "3"

services:
  db:
    image: postgres:14.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: go2
      POSTGRES_DB: go2
      POSTGRES_PASSWORD: bananas
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth:
    image: qlik/simple-oidc-provider
    ports:
      - "8081:8081"
    environment:
      REDIRECTS: http://localhost:8080/auth/callback
      PORT: 8081
      IDP_NAME: http://localhost:8081/

volumes:
  postgres_data:
