name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ci-build
          save-if: false
      - name: Run clippy
        run: cargo clippy --verbose --workspace
      - name: Check formatting
        run: cargo fmt --check --verbose
